RATING = "rating"
ID = "id"
IS_SERIES = "isSeries"
AVG_TIME = "avrgTime"
EPISODE_COUNT = "episodeCount"
TITLE = "title"
TIME = "time"
GENRES = "genres"
CAST = "cast"
DIRECTORS = "directors"
COUNTRIES = "countries"

DATA_FILE_NAME = "deneme"
RATING_FILE_NAME = "rating-"
PIECES_STORAGE_FILE_NAME = "pieces"
